# Generated by Django 3.1.3 on 2021-04-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaApp', '0003_auto_20210413_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrederModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('phoneno', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('ordereditem', models.CharField(max_length=50)),
            ],
        ),
    ]
