# Generated by Django 3.1.3 on 2021-04-16 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaApp', '0005_auto_20210415_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='ordereditem',
            new_name='ordereditems',
        ),
    ]
