# Generated by Django 3.1.3 on 2021-04-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaApp', '0006_auto_20210416_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='phoneno',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='phoneno',
            field=models.CharField(max_length=50),
        ),
    ]
