# Generated by Django 3.1.3 on 2021-04-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaApp', '0007_auto_20210416_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzamodel',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
