# Generated by Django 3.1.3 on 2021-04-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaApp', '0008_auto_20210416_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(default='pending:', max_length=50),
            preserve_default=False,
        ),
    ]
